name: Go

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    - name: Download dependencies
      run: go mod download -x
    - name: Test
      run: go test -v ./...
    - name: Build
      run: |
        cd hello
        go build -v -o hello .
        ./hello -g Welcome Bitrise 
        ./hello -r -g Welcome Bitrise
